# Generated by Django 6.0.1 on 2026-02-23 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_id'),
        ('organizations', '0008_alter_positiontype_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization'),
        ),
    ]
