# Generated by Django 6.0.1 on 2026-02-21 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_question_is_required_question_max_value_and_more'),
        ('organizations', '0008_alter_positiontype_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclude_self', models.BooleanField(default=True)),
                ('evaluatee_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.positiontype')),
                ('evaluatee_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.organizationunit')),
                ('evaluator_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.positiontype')),
                ('evaluator_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.organizationunit')),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_rules', to='evaluations.evaluationform')),
            ],
        ),
    ]
