# Generated by Django 6.0.1 on 2026-02-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_rename_is_published_evaluationform_results_released_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationform',
            name='type',
        ),
    ]
