# Generated by Django 6.0.1 on 2026-02-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_add_created_at_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationform',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
