# Generated by Django 6.0.1 on 2026-02-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_accomplishment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='proof_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
