# Generated by Django 6.0.1 on 2026-02-27 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_organizationrole_is_active'),
        ('portfolio', '0005_accomplishment_comments_accomplishment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishment',
            name='organization_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='accomplishments', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accomplishment',
            name='id',
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
