# Generated by Django 5.2.6 on 2026-02-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_accomplishment_organization_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
