# Generated by Django 6.0.4 on 2026-04-09 00:00

from django.db import migrations


def dedupe_memberships(apps, schema_editor):
    Membership = apps.get_model('organizations', 'Membership')

    seen = set()
    to_delete_ids = []

    # Prefer active memberships, then oldest by id within each duplicate group.
    queryset = (
        Membership.objects
        .order_by('user_id_id', 'unit_id_id', 'position_id_id', '-is_active', 'id')
        .values_list('id', 'user_id_id', 'unit_id_id', 'position_id_id')
    )

    for membership_id, user_id, unit_id, position_id in queryset.iterator():
        key = (user_id, unit_id, position_id)
        if key in seen:
            to_delete_ids.append(membership_id)
        else:
            seen.add(key)

    if to_delete_ids:
        Membership.objects.filter(id__in=to_delete_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_alter_joinrequest_id_alter_membership_id_and_more'),
        ('organizations', '0014_alter_organization_display_picture_and_more'),
    ]

    operations = [
        migrations.RunPython(dedupe_memberships, migrations.RunPython.noop),
    ]
