# Generated by Django 6.0.4 on 2026-04-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_dedupe_membership'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('user_id', 'unit_id', 'position_id')},
        ),
    ]
