# Generated by Django 6.0.1 on 2026-02-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_membership_role_alter_membership_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[(
                'Admin', 'Admin'), ('Member', 'Member')], default='Member', max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
