# Generated by Django 6.0.1 on 2026-02-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_joinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationunit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='positiontype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='unittype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
