# Generated by Django 6.0.1 on 2026-02-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organizationunit_is_active_positiontype_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationunit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
