# Generated by Django 6.0.1 on 2026-02-21 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_organizationunit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positiontype',
            name='rank',
            field=models.IntegerField(help_text='1 for Head, higher numbers for lower rank', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
