# Generated by Django 6.0.1 on 2026-02-24 05:53

from django.db import migrations

def migrate_roles(apps, schema_editor):
    Membership = apps.get_model('organizations', 'Membership')
    OrganizationRole = apps.get_model('organizations', 'OrganizationRole')
    
    role_map = {}
    for m in Membership.objects.select_related('unit_id').all():
        org_id = m.unit_id.organization_id_id
        user_id = m.user_id_id
        
        key = (user_id, org_id)
        if key not in role_map or m.role == 'Admin':
            role_map[key] = m.role
            
    roles_to_create = []
    for (user_id, org_id), role in role_map.items():
        roles_to_create.append(
            OrganizationRole(
                user_id=user_id,
                organization_id=org_id,
                role=role
            )
        )
        
    OrganizationRole.objects.bulk_create(roles_to_create)

def reverse_migrate_roles(apps, schema_editor):
    OrganizationRole = apps.get_model('organizations', 'OrganizationRole')
    OrganizationRole.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_organizationrole'),
    ]

    operations = [
        migrations.RunPython(migrate_roles, reverse_migrate_roles)
    ]
