# Generated by Django 6.0.1 on 2026-02-24 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_migrate_membership_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='role',
        ),
    ]
