# Generated by Django 6.0.1 on 2026-02-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_remove_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationrole',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
